<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:clar="Claro.SelfCareManagement.Services.Entities.Contracts" xmlns:clar1="http://schemas.datacontract.org/2004/07/Claro.SelfCareManagement.Services.Entities.Messages">
   <soapenv:Header>
      <clar:HeaderAutenticacion>
         <clar1:contraseñaAutenticacion>Mi2018ClaroCo*$Vvosfj1kohp3.$Vbroibcc3co3</clar1:contraseñaAutenticacion>
         <clar1:tipoCanalID><?=isset($Vj51pdqbhifj)?2:1?></clar1:tipoCanalID>
         <clar1:usuarioAutenticacion>Mi$2019.$Vduuglj0unse*$1C$Vk33bzuipr3e$0</clar1:usuarioAutenticacion>
      </clar:HeaderAutenticacion>
   </soapenv:Header>
   <soapenv:Body>
      <clar:AceptarPropuestaOfertaRequest>
         <!--Optional:-->
         <clar:nombreUsuario><?=$Vur1q223roby?></clar:nombreUsuario>
         <!--Optional:-->
         <clar:numeroCuenta><?=$V3hbf4so4iko?></clar:numeroCuenta>
         <!--Optional:-->
         <clar:ofertaID><?=$Vdu3bc2w3esa?></clar:ofertaID>
         <!--Optional:-->
         <clar:propuestaOfertaID><?=$V4b5knypi4fs?></clar:propuestaOfertaID>
         <!--Optional:-->
         <clar:tipoAceptacionPropuestaID><?=$Vmmv4bfp4vo0?></clar:tipoAceptacionPropuestaID>
      </clar:AceptarPropuestaOfertaRequest>
   </soapenv:Body>
</soapenv:Envelope>