<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:clar="Claro.SelfCareManagement.Services.Entities.Contracts" xmlns:clar1="http://schemas.datacontract.org/2004/07/Claro.SelfCareManagement.Services.Entities.Messages">
   <soapenv:Header>
      <clar:HeaderAutenticacion>
         <clar1:contraseñaAutenticacion>Mi2018ClaroCo*$Vvosfj1kohp3.$Vbroibcc3co3</clar1:contraseñaAutenticacion>
         <clar1:tipoCanalID><?=isset($Vj51pdqbhifj)?2:1?></clar1:tipoCanalID>
         <clar1:usuarioAutenticacion>Mi$2019.$Vduuglj0unse*$1C$Vk33bzuipr3e$0</clar1:usuarioAutenticacion>
      </clar:HeaderAutenticacion>
   </soapenv:Header>
   <soapenv:Body>
		<clar:activarDesactivarServicio>
			<!--Optional:-->
			<clar:RequestServicio>
				<clar1:accion><?=$Vi3ex0x5a4sl?></clar1:accion>
				<clar1:mdrs>0</clar1:mdrs>
				<clar1:min><?=$V3hbf4so4iko?></clar1:min>
				<clar1:serv><?=$Vvqv220tasab?></clar1:serv>
				<clar1:spCode><?=$Vzskwov3nkbo?></clar1:spCode>
				<clar1:spCodeValid></clar1:spCodeValid>
				<clar1:tickler>0</clar1:tickler>
			</clar:RequestServicio>
      </clar:activarDesactivarServicio>
   </soapenv:Body>
</soapenv:Envelope>