{
 "mapCollection":{
    "authentication":{
       "token":"VkdGMGFXTTZVMmxqWTI5dQ=="
    },
    "values":[{
      "arrayValue":"request",
      "mapArrayValue":[{
          "name":"MIN",
          "singleValue":"57<?=$V3hbf4so4iko?>"
      },{
          "name":"TipoAbonado",
          "singleValue":"PostPago"
      },{
          "name":"TipoConsulta",
          "singleValue":"ConsumoQuotaLocalBlindaje"
      }]
    }]
  }
}