<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://servicios.autolegalizacion.claro.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:legalizarLinea>
         <!--Optional:-->
         <RequestLinea>
           <min><?=$V3hbf4so4iko?></min>
            <canal>MiClaro</canal>
            <evento>1</evento>
            <tipoDocumento><?=$Vcfzis3ca5nv?></tipoDocumento>
            <numeroDocumento><?=$Vbbhadzcf3q5?></numeroDocumento>
            <fechaExpedicion><?=$Vmflplvsxtqs?></fechaExpedicion>
            <apellido><?=$Vcfuma51n1le?></apellido>
            <segundoApellido><?=$Vj2zuouufqds?></segundoApellido>
            <nombre><?=$Vwzmz1dvggot?></nombre>
            <direccion><?=$Vtt5lms041w2?></direccion>
            <ciudad><?=$V1mccspyvfe0?></ciudad>
            <departamento><?=$Vbnriemdgxet?></departamento>
            <municipio><?=$Vripxsb2y5ic?></municipio>
            <idTransaccion>1</idTransaccion>
         </RequestLinea>
      </ser:legalizarLinea>
   </soapenv:Body>
</soapenv:Envelope>