<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://www.ericsson.com/esb/data/generico/CommonTypes/v2/" xmlns:v1="http://www.ericsson.com/esb/billingManagement/searchFinancialTransactionsRequest/v1.0/">
   <soapenv:Header>
      <v2:headerRequest>
         <v2:channel></v2:channel>
         <v2:idApplication></v2:idApplication>
         <v2:userApplication></v2:userApplication>
         <v2:userSession></v2:userSession>
         <v2:idESBTransaction></v2:idESBTransaction>
         <v2:idBusinessTransaction></v2:idBusinessTransaction>
         <v2:additionalNode>?</v2:additionalNode>
      </v2:headerRequest>
   </soapenv:Header>
   <soapenv:Body>
      <v1:searchFinancialTransactionsRequest>
         <subscriberNumber><?=$Vqhzkfsafzrc->AccountId?></subscriberNumber>
         <documentType><?=$Vqhzkfsafzrc->documentType?></documentType>
         <documentNumber><?=$Vqhzkfsafzrc->documentNumber?></documentNumber>
         <billingAccount></billingAccount>
         <entryDateFrom><?=$Vqhzkfsafzrc->fecha?></entryDateFrom>
         <entryDateUntil></entryDateUntil>
         <transactionStatus></transactionStatus>
         <transactionId></transactionId>
       <searchLimit>10</searchLimit>
      </v1:searchFinancialTransactionsRequest>
   </soapenv:Body>
</soapenv:Envelope>