<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v1="http://www.americamovil.com/schema/namespace/ContractManagement/v1">
<soapenv:Header>
    <ServiceGatewayHeader>
        <codIdioma>EN</codIdioma>
        <systemId>SELFSERVICE</systemId>
        <userProfileId><?=$Vqhzkfsafzrc->UserProfileID?></userProfileId>
        <operationId>retrieveContractDocument</operationId>
        <IPServer>9.129.59.6</IPServer>
        <TipoCanal>MB</TipoCanal>
        <VersionServicio>1.0</VersionServicio>
        <VersionEndpoint>1.0</VersionEndpoint>
        <Notification>false</Notification>
    </ServiceGatewayHeader>
</soapenv:Header>
   <soapenv:Body>
      <v1:retrieveContractDocument>
         <LineOfBusiness><?=$Vqhzkfsafzrc->LineOfBusiness?></LineOfBusiness>
         <UserProfileId><?=$Vqhzkfsafzrc->UserProfileID?></UserProfileId>
         <AccountId><?=$Vqhzkfsafzrc->AccountId?></AccountId>
      </v1:retrieveContractDocument>
   </soapenv:Body>
</soapenv:Envelope>