<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://www.ericsson.com/esb/data/generico/CommonTypes/v2/" xmlns:v1="http://www.ericsson.com/esb/message/customer/deleteFrequentNumberRequest/v1.0">
   <soapenv:Header>
       <v2:headerRequest>
         <v2:channel>USSD</v2:channel>
         <v2:idApplication>usdapp1</v2:idApplication>
         <v2:userApplication>jjuser</v2:userApplication>
         <v2:userSession/>
         <v2:idESBTransaction>1234567890</v2:idESBTransaction>
         <v2:idBusinessTransaction>1234567890</v2:idBusinessTransaction>
         <v2:startDate>20150528T10:11:21-0500</v2:startDate>
         <v2:additionalNode/>
      </v2:headerRequest>
   </soapenv:Header>
   <soapenv:Body>
      <v1:deleteFrequentNumberRequest>
         <subscriberNumber>57<?=$Vqhzkfsafzrc->AccountId?></subscriberNumber>
         <frequentNumber>57<?=$Vqhzkfsafzrc->PhoneNumber?></frequentNumber>
          <!--<frequentType><?=$Vqhzkfsafzrc->FrequentNumberType?></frequentType>-->
          <frequentType>6418</frequentType>
         <poId>PO_TelPosFAF</poId>
         <originHostName>hostname</originHostName>
         <originNodeType>UGW</originNodeType>
      </v1:deleteFrequentNumberRequest>
   </soapenv:Body>
</soapenv:Envelope>