<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ser="http://servicios.autolegalizacion.claro.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <ser:validarDatosDemograficos>
         <!--Optional:-->
         <RequestDatosDemograficos>
            <min><?=$Vqhzkfsafzrc->AccountId?></min>
            <canal>MiClaro</canal>
            <tipoDocumento><?=$Vqhzkfsafzrc->DocumentType?></tipoDocumento>
            <numeroDocumento><?=$Vqhzkfsafzrc->DocumentNumber?></numeroDocumento>
            <!--Optional:-->
            <fechaExpedicion><?=$Vqhzkfsafzrc->fechaExpedicion?></fechaExpedicion>
            <!--Optional:-->
            <apellido><?=$Vqhzkfsafzrc->apellido?></apellido>
            <idTransaccion>1</idTransaccion>
         </RequestDatosDemograficos>
      </ser:validarDatosDemograficos>
   </soapenv:Body>
</soapenv:Envelope>