<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:clar="Claro.SelfCareManagement.Services.Entities.Contracts" xmlns:clar1="http://schemas.datacontract.org/2004/07/Claro.SelfCareManagement.Services.Entities.Messages">
   <soapenv:Header>
      <clar:HeaderAutenticacion>
         <clar1:contraseñaAutenticacion>Mi2018ClaroCo*$Vvosfj1kohp3.$Vbroibcc3co3</clar1:contraseñaAutenticacion>
         <clar1:tipoCanalID><?=isset($Vj51pdqbhifj)?2:1?></clar1:tipoCanalID>
         <clar1:usuarioAutenticacion>Mi$2019.$Vduuglj0unse*$1C$Vk33bzuipr3e$0</clar1:usuarioAutenticacion>
      </clar:HeaderAutenticacion>
   </soapenv:Header>
   <soapenv:Body>
      <clar:ConfigurarFacturaElectronicaMovilRequest>
         <!--Optional:-->
         <clar:facturaElectronicaMovilRequest>
            <clar1:correoElectronicoNotificacion><?=$Vz3jaxkkbo1o?></clar1:correoElectronicoNotificacion>
            <clar1:esActivacionFacturaElectronica><?=((intval($Vkcuhmulb003)==1)?"true":"false")?></clar1:esActivacionFacturaElectronica>
            <clar1:nombreUsuario><?=$Vur1q223roby?></clar1:nombreUsuario>
            <clar1:numeroCuenta><?=$V3hbf4so4iko?></clar1:numeroCuenta>
            <clar1:numeroCuentaNotificacion><?=$V0sje5ijz0rw?></clar1:numeroCuentaNotificacion>
         </clar:facturaElectronicaMovilRequest>
      </clar:ConfigurarFacturaElectronicaMovilRequest>
   </soapenv:Body>
</soapenv:Envelope>