<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://www.ericsson.com/esb/data/generico/CommonTypes/v2/" 
xmlns:v1="http://www.ericsson.com/esb/message/paymentReferencesMgtm/getPaymentReferencesRequest/v1.0">
   <soapenv:Header>
      <v2:headerRequest>
         <v2:channel></v2:channel>
         <v2:idApplication></v2:idApplication>
         <v2:userApplication></v2:userApplication>
         <v2:userSession></v2:userSession>
         <v2:idESBTransaction></v2:idESBTransaction>
         <v2:idBusinessTransaction></v2:idBusinessTransaction>
         <v2:startDate></v2:startDate>
         <v2:additionalNode></v2:additionalNode>
      </v2:headerRequest>
   </soapenv:Header>
   <soapenv:Body>
      <v1:GetPaymentReferencesRequest>
         <subscriberNumber><?=$Vqhzkfsafzrc->numeroCuenta?></subscriberNumber>
         <identificationType>1</identificationType>
         <identificationNumber>123123</identificationNumber>
         <customerId></customerId>
         <paymentReference></paymentReference>
         <billingAccount></billingAccount>
      </v1:GetPaymentReferencesRequest>
   </soapenv:Body>
</soapenv:Envelope>