<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v2="http://www.ericsson.com/esb/data/generico/CommonTypes/v2/" xmlns:v21="http://www.ericsson.com/esb/message/customer/getSubscriberPackagesRequest/v2.0">
   <soapenv:Header>
      <v2:headerRequest>
         <v2:channel></v2:channel>
         <v2:idApplication></v2:idApplication>
         <v2:userApplication></v2:userApplication>
         <v2:userSession></v2:userSession>
         <v2:idESBTransaction></v2:idESBTransaction>
         <v2:idBusinessTransaction></v2:idBusinessTransaction>
         <v2:startDate></v2:startDate>
         <v2:additionalNode></v2:additionalNode>
      </v2:headerRequest>
   </soapenv:Header>
   <soapenv:Body>
      <v21:getSubscriberPackagesRequest>
         <subscriberNumber>57<?=$Vqhzkfsafzrc->AccountId?></subscriberNumber>
         <identificationType></identificationType>
         <identificationNumber></identificationNumber>
         <billingAccount></billingAccount>
         <product></product>
         <customerId></customerId>
         <contractId></contractId>
         <serviceType></serviceType>
         <returnService>true</returnService>
         <returnSubscription>true</returnSubscription>
      </v21:getSubscriberPackagesRequest>
   </soapenv:Body>
</soapenv:Envelope>