<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:clar="Claro.SelfCareManagement.Services.Entities.Contracts" xmlns:clar1="http://schemas.datacontract.org/2004/07/Claro.SelfCareManagement.Services.Entities.Messages">
   <soapenv:Header>
      <clar:HeaderAutenticacion>
         <clar1:contraseñaAutenticacion>Mi2018ClaroCo*$Vulisw0g0y15.$Vz3iq0a20pcw</clar1:contraseñaAutenticacion>
         <clar1:tipoCanalID><?=isset($V34pc0h2hbai)?2:1?></clar1:tipoCanalID>
         <clar1:usuarioAutenticacion>Mi$2019.$Vozz1pec1mnf*$1C$Vm3szalwqx1l$0</clar1:usuarioAutenticacion>
      </clar:HeaderAutenticacion>
   </soapenv:Header>
   <soapenv:Body>
		<clar:activarDesactivarServicio>
			<!--Optional:-->
			<clar:RequestServicio>
				<clar1:accion><?=$Vqhzkfsafzrc->accion?></clar1:accion>
				<clar1:mdrs>0</clar1:mdrs>
				<clar1:min><?=$Vqhzkfsafzrc->AccountId?></clar1:min>
				<clar1:serv><?=$Vqhzkfsafzrc->servicio?></clar1:serv>
				<clar1:spCode><?=$Vqhzkfsafzrc->paquete?></clar1:spCode>
				<clar1:spCodeValid></clar1:spCodeValid>
				<clar1:tickler>0</clar1:tickler>
			</clar:RequestServicio>
      </clar:activarDesactivarServicio>
   </soapenv:Body>
</soapenv:Envelope>